version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: granblue-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: granblue_db
      POSTGRES_USER: granblue_user
      POSTGRES_PASSWORD: granblue_password
    volumes:
      - ./postgres_data:/home/dnekfl77/storage/postgresql/data

volumes:
  postgres_data: