server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/granblue_db
    username: granblue_user
    password: granblue_password
  jpa:
    hibernate:
      ddl-auto: update
