server:
  servlet:
    context-path: /api
spring:
  profiles:
    active: local
  application:
    name: granblue-api
  devtools:
    restart:
      enabled: false # 기본적으로 자동 재시작 비활성화 (운영/개발 서버 안전성)
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  data:
    jdbc:
      dialect: postgresql
jwt:
  secret: v1TqO1N0h3R6t4w1o8V9f5P1k2N0h3R6t4w1o8V9f5P1k2N0h3R6t4w1o8V9f5P1
logging:
  level:
    root: INFO
    com.granblue.api: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
